name: Tests

on:
  push:
  pull_request:

jobs:
  tests:
    name: PHP ${{ matrix.php }}; Laravel ${{ matrix.laravel }}
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        php: ['8.0', '8.1', '8.2']
        laravel: ['9', '10']
        exclude:
          - { laravel: '10', php: '8.0' }

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          ini-values: error_reporting=E_ALL
          php-version: ${{ matrix.php }}
          tools: composer:v2
          coverage: none

      - name: Setup Problem Matchers
        run: echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

      - name: Select Laravel 8
        uses: nick-invision/retry@v2.8.2
        with:
          timeout_minutes: 5
          max_attempts: 5
          command: composer require "laravel/framework:8.*" "phpunit/phpunit:^9.3.7" --no-update --no-interaction
        if: "matrix.laravel == '8'"

      - name: Select Laravel 9
        uses: nick-invision/retry@v2.8.2
        with:
          timeout_minutes: 5
          max_attempts: 5
          command: composer require "laravel/framework:9.*" "phpunit/phpunit:^9.3.7" --no-update --no-interaction
        if: "matrix.laravel == '9'"

      - name: Install PHP Dependencies
        uses: nick-invision/retry@v2.8.2
        with:
          timeout_minutes: 5
          max_attempts: 5
          command: composer update --no-interaction --no-progress

      - name: Execute PHPUnit
        run: vendor/bin/phpunit
